// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KFDataMessage.proto

#ifndef PROTOBUF_KFDataMessage_2eproto__INCLUDED
#define PROTOBUF_KFDataMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "KFCommonMessage.pb.h"
// @@protoc_insertion_point(includes)

namespace KFMsg {

// Internal implementation detail -- do not call these.
void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
void protobuf_AssignDesc_KFDataMessage_2eproto();
void protobuf_ShutdownFile_KFDataMessage_2eproto();

class MsgEnterGame;
class MsgSyncUpdateData;
class MsgSyncAddData;
class MsgSyncRemoveData;
class MsgTellQueryPlayer;
class MsgTellQueryBasic;

enum DataProtocol {
  MSG_LOGIN_ENTER_GAME = 10,
  MSG_SYNC_UPDATE_DATA = 11,
  MSG_SYNC_ADD_DATA = 12,
  MSG_SYNC_REMOVE_DATA = 13,
  MSG_TELL_QUERY_PLAYER = 14,
  MSG_TELL_QUERY_BASIC = 15
};
LIBPROTOC_EXPORT bool DataProtocol_IsValid(int value);
const DataProtocol DataProtocol_MIN = MSG_LOGIN_ENTER_GAME;
const DataProtocol DataProtocol_MAX = MSG_TELL_QUERY_BASIC;
const int DataProtocol_ARRAYSIZE = DataProtocol_MAX + 1;

LIBPROTOC_EXPORT const ::google::protobuf::EnumDescriptor* DataProtocol_descriptor();
inline const ::std::string& DataProtocol_Name(DataProtocol value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataProtocol_descriptor(), value);
}
inline bool DataProtocol_Parse(
    const ::std::string& name, DataProtocol* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataProtocol>(
    DataProtocol_descriptor(), name, value);
}
// ===================================================================

class LIBPROTOC_EXPORT MsgEnterGame : public ::google::protobuf::Message {
 public:
  MsgEnterGame();
  virtual ~MsgEnterGame();

  MsgEnterGame(const MsgEnterGame& from);

  inline MsgEnterGame& operator=(const MsgEnterGame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgEnterGame& default_instance();

  void Swap(MsgEnterGame* other);

  // implements Message ----------------------------------------------

  MsgEnterGame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgEnterGame& from);
  void MergeFrom(const MsgEnterGame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .KFMsg.PBObject playerdata = 1;
  inline bool has_playerdata() const;
  inline void clear_playerdata();
  static const int kPlayerdataFieldNumber = 1;
  inline const ::KFMsg::PBObject& playerdata() const;
  inline ::KFMsg::PBObject* mutable_playerdata();
  inline ::KFMsg::PBObject* release_playerdata();
  inline void set_allocated_playerdata(::KFMsg::PBObject* playerdata);

  // required uint64 servertime = 2;
  inline bool has_servertime() const;
  inline void clear_servertime();
  static const int kServertimeFieldNumber = 2;
  inline ::google::protobuf::uint64 servertime() const;
  inline void set_servertime(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:KFMsg.MsgEnterGame)
 private:
  inline void set_has_playerdata();
  inline void clear_has_playerdata();
  inline void set_has_servertime();
  inline void clear_has_servertime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::KFMsg::PBObject* playerdata_;
  ::google::protobuf::uint64 servertime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
  friend void protobuf_AssignDesc_KFDataMessage_2eproto();
  friend void protobuf_ShutdownFile_KFDataMessage_2eproto();

  void InitAsDefaultInstance();
  static MsgEnterGame* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT MsgSyncUpdateData : public ::google::protobuf::Message {
 public:
  MsgSyncUpdateData();
  virtual ~MsgSyncUpdateData();

  MsgSyncUpdateData(const MsgSyncUpdateData& from);

  inline MsgSyncUpdateData& operator=(const MsgSyncUpdateData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSyncUpdateData& default_instance();

  void Swap(MsgSyncUpdateData* other);

  // implements Message ----------------------------------------------

  MsgSyncUpdateData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSyncUpdateData& from);
  void MergeFrom(const MsgSyncUpdateData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .KFMsg.PBObject pbdata = 1;
  inline bool has_pbdata() const;
  inline void clear_pbdata();
  static const int kPbdataFieldNumber = 1;
  inline const ::KFMsg::PBObject& pbdata() const;
  inline ::KFMsg::PBObject* mutable_pbdata();
  inline ::KFMsg::PBObject* release_pbdata();
  inline void set_allocated_pbdata(::KFMsg::PBObject* pbdata);

  // @@protoc_insertion_point(class_scope:KFMsg.MsgSyncUpdateData)
 private:
  inline void set_has_pbdata();
  inline void clear_has_pbdata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::KFMsg::PBObject* pbdata_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
  friend void protobuf_AssignDesc_KFDataMessage_2eproto();
  friend void protobuf_ShutdownFile_KFDataMessage_2eproto();

  void InitAsDefaultInstance();
  static MsgSyncUpdateData* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT MsgSyncAddData : public ::google::protobuf::Message {
 public:
  MsgSyncAddData();
  virtual ~MsgSyncAddData();

  MsgSyncAddData(const MsgSyncAddData& from);

  inline MsgSyncAddData& operator=(const MsgSyncAddData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSyncAddData& default_instance();

  void Swap(MsgSyncAddData* other);

  // implements Message ----------------------------------------------

  MsgSyncAddData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSyncAddData& from);
  void MergeFrom(const MsgSyncAddData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .KFMsg.PBObject pbdata = 1;
  inline bool has_pbdata() const;
  inline void clear_pbdata();
  static const int kPbdataFieldNumber = 1;
  inline const ::KFMsg::PBObject& pbdata() const;
  inline ::KFMsg::PBObject* mutable_pbdata();
  inline ::KFMsg::PBObject* release_pbdata();
  inline void set_allocated_pbdata(::KFMsg::PBObject* pbdata);

  // @@protoc_insertion_point(class_scope:KFMsg.MsgSyncAddData)
 private:
  inline void set_has_pbdata();
  inline void clear_has_pbdata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::KFMsg::PBObject* pbdata_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
  friend void protobuf_AssignDesc_KFDataMessage_2eproto();
  friend void protobuf_ShutdownFile_KFDataMessage_2eproto();

  void InitAsDefaultInstance();
  static MsgSyncAddData* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT MsgSyncRemoveData : public ::google::protobuf::Message {
 public:
  MsgSyncRemoveData();
  virtual ~MsgSyncRemoveData();

  MsgSyncRemoveData(const MsgSyncRemoveData& from);

  inline MsgSyncRemoveData& operator=(const MsgSyncRemoveData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSyncRemoveData& default_instance();

  void Swap(MsgSyncRemoveData* other);

  // implements Message ----------------------------------------------

  MsgSyncRemoveData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSyncRemoveData& from);
  void MergeFrom(const MsgSyncRemoveData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .KFMsg.PBObject pbdata = 1;
  inline bool has_pbdata() const;
  inline void clear_pbdata();
  static const int kPbdataFieldNumber = 1;
  inline const ::KFMsg::PBObject& pbdata() const;
  inline ::KFMsg::PBObject* mutable_pbdata();
  inline ::KFMsg::PBObject* release_pbdata();
  inline void set_allocated_pbdata(::KFMsg::PBObject* pbdata);

  // @@protoc_insertion_point(class_scope:KFMsg.MsgSyncRemoveData)
 private:
  inline void set_has_pbdata();
  inline void clear_has_pbdata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::KFMsg::PBObject* pbdata_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
  friend void protobuf_AssignDesc_KFDataMessage_2eproto();
  friend void protobuf_ShutdownFile_KFDataMessage_2eproto();

  void InitAsDefaultInstance();
  static MsgSyncRemoveData* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT MsgTellQueryPlayer : public ::google::protobuf::Message {
 public:
  MsgTellQueryPlayer();
  virtual ~MsgTellQueryPlayer();

  MsgTellQueryPlayer(const MsgTellQueryPlayer& from);

  inline MsgTellQueryPlayer& operator=(const MsgTellQueryPlayer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTellQueryPlayer& default_instance();

  void Swap(MsgTellQueryPlayer* other);

  // implements Message ----------------------------------------------

  MsgTellQueryPlayer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTellQueryPlayer& from);
  void MergeFrom(const MsgTellQueryPlayer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .KFMsg.PBObject player = 1;
  inline bool has_player() const;
  inline void clear_player();
  static const int kPlayerFieldNumber = 1;
  inline const ::KFMsg::PBObject& player() const;
  inline ::KFMsg::PBObject* mutable_player();
  inline ::KFMsg::PBObject* release_player();
  inline void set_allocated_player(::KFMsg::PBObject* player);

  // @@protoc_insertion_point(class_scope:KFMsg.MsgTellQueryPlayer)
 private:
  inline void set_has_player();
  inline void clear_has_player();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::KFMsg::PBObject* player_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
  friend void protobuf_AssignDesc_KFDataMessage_2eproto();
  friend void protobuf_ShutdownFile_KFDataMessage_2eproto();

  void InitAsDefaultInstance();
  static MsgTellQueryPlayer* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT MsgTellQueryBasic : public ::google::protobuf::Message {
 public:
  MsgTellQueryBasic();
  virtual ~MsgTellQueryBasic();

  MsgTellQueryBasic(const MsgTellQueryBasic& from);

  inline MsgTellQueryBasic& operator=(const MsgTellQueryBasic& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTellQueryBasic& default_instance();

  void Swap(MsgTellQueryBasic* other);

  // implements Message ----------------------------------------------

  MsgTellQueryBasic* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTellQueryBasic& from);
  void MergeFrom(const MsgTellQueryBasic& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .KFMsg.PBObject player = 1;
  inline bool has_player() const;
  inline void clear_player();
  static const int kPlayerFieldNumber = 1;
  inline const ::KFMsg::PBObject& player() const;
  inline ::KFMsg::PBObject* mutable_player();
  inline ::KFMsg::PBObject* release_player();
  inline void set_allocated_player(::KFMsg::PBObject* player);

  // @@protoc_insertion_point(class_scope:KFMsg.MsgTellQueryBasic)
 private:
  inline void set_has_player();
  inline void clear_has_player();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::KFMsg::PBObject* player_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void LIBPROTOC_EXPORT protobuf_AddDesc_KFDataMessage_2eproto();
  friend void protobuf_AssignDesc_KFDataMessage_2eproto();
  friend void protobuf_ShutdownFile_KFDataMessage_2eproto();

  void InitAsDefaultInstance();
  static MsgTellQueryBasic* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgEnterGame

// required .KFMsg.PBObject playerdata = 1;
inline bool MsgEnterGame::has_playerdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgEnterGame::set_has_playerdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgEnterGame::clear_has_playerdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgEnterGame::clear_playerdata() {
  if (playerdata_ != NULL) playerdata_->::KFMsg::PBObject::Clear();
  clear_has_playerdata();
}
inline const ::KFMsg::PBObject& MsgEnterGame::playerdata() const {
  return playerdata_ != NULL ? *playerdata_ : *default_instance_->playerdata_;
}
inline ::KFMsg::PBObject* MsgEnterGame::mutable_playerdata() {
  set_has_playerdata();
  if (playerdata_ == NULL) playerdata_ = new ::KFMsg::PBObject;
  return playerdata_;
}
inline ::KFMsg::PBObject* MsgEnterGame::release_playerdata() {
  clear_has_playerdata();
  ::KFMsg::PBObject* temp = playerdata_;
  playerdata_ = NULL;
  return temp;
}
inline void MsgEnterGame::set_allocated_playerdata(::KFMsg::PBObject* playerdata) {
  delete playerdata_;
  playerdata_ = playerdata;
  if (playerdata) {
    set_has_playerdata();
  } else {
    clear_has_playerdata();
  }
}

// required uint64 servertime = 2;
inline bool MsgEnterGame::has_servertime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgEnterGame::set_has_servertime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgEnterGame::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgEnterGame::clear_servertime() {
  servertime_ = GOOGLE_ULONGLONG(0);
  clear_has_servertime();
}
inline ::google::protobuf::uint64 MsgEnterGame::servertime() const {
  return servertime_;
}
inline void MsgEnterGame::set_servertime(::google::protobuf::uint64 value) {
  set_has_servertime();
  servertime_ = value;
}

// -------------------------------------------------------------------

// MsgSyncUpdateData

// required .KFMsg.PBObject pbdata = 1;
inline bool MsgSyncUpdateData::has_pbdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSyncUpdateData::set_has_pbdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSyncUpdateData::clear_has_pbdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSyncUpdateData::clear_pbdata() {
  if (pbdata_ != NULL) pbdata_->::KFMsg::PBObject::Clear();
  clear_has_pbdata();
}
inline const ::KFMsg::PBObject& MsgSyncUpdateData::pbdata() const {
  return pbdata_ != NULL ? *pbdata_ : *default_instance_->pbdata_;
}
inline ::KFMsg::PBObject* MsgSyncUpdateData::mutable_pbdata() {
  set_has_pbdata();
  if (pbdata_ == NULL) pbdata_ = new ::KFMsg::PBObject;
  return pbdata_;
}
inline ::KFMsg::PBObject* MsgSyncUpdateData::release_pbdata() {
  clear_has_pbdata();
  ::KFMsg::PBObject* temp = pbdata_;
  pbdata_ = NULL;
  return temp;
}
inline void MsgSyncUpdateData::set_allocated_pbdata(::KFMsg::PBObject* pbdata) {
  delete pbdata_;
  pbdata_ = pbdata;
  if (pbdata) {
    set_has_pbdata();
  } else {
    clear_has_pbdata();
  }
}

// -------------------------------------------------------------------

// MsgSyncAddData

// required .KFMsg.PBObject pbdata = 1;
inline bool MsgSyncAddData::has_pbdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSyncAddData::set_has_pbdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSyncAddData::clear_has_pbdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSyncAddData::clear_pbdata() {
  if (pbdata_ != NULL) pbdata_->::KFMsg::PBObject::Clear();
  clear_has_pbdata();
}
inline const ::KFMsg::PBObject& MsgSyncAddData::pbdata() const {
  return pbdata_ != NULL ? *pbdata_ : *default_instance_->pbdata_;
}
inline ::KFMsg::PBObject* MsgSyncAddData::mutable_pbdata() {
  set_has_pbdata();
  if (pbdata_ == NULL) pbdata_ = new ::KFMsg::PBObject;
  return pbdata_;
}
inline ::KFMsg::PBObject* MsgSyncAddData::release_pbdata() {
  clear_has_pbdata();
  ::KFMsg::PBObject* temp = pbdata_;
  pbdata_ = NULL;
  return temp;
}
inline void MsgSyncAddData::set_allocated_pbdata(::KFMsg::PBObject* pbdata) {
  delete pbdata_;
  pbdata_ = pbdata;
  if (pbdata) {
    set_has_pbdata();
  } else {
    clear_has_pbdata();
  }
}

// -------------------------------------------------------------------

// MsgSyncRemoveData

// required .KFMsg.PBObject pbdata = 1;
inline bool MsgSyncRemoveData::has_pbdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSyncRemoveData::set_has_pbdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSyncRemoveData::clear_has_pbdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSyncRemoveData::clear_pbdata() {
  if (pbdata_ != NULL) pbdata_->::KFMsg::PBObject::Clear();
  clear_has_pbdata();
}
inline const ::KFMsg::PBObject& MsgSyncRemoveData::pbdata() const {
  return pbdata_ != NULL ? *pbdata_ : *default_instance_->pbdata_;
}
inline ::KFMsg::PBObject* MsgSyncRemoveData::mutable_pbdata() {
  set_has_pbdata();
  if (pbdata_ == NULL) pbdata_ = new ::KFMsg::PBObject;
  return pbdata_;
}
inline ::KFMsg::PBObject* MsgSyncRemoveData::release_pbdata() {
  clear_has_pbdata();
  ::KFMsg::PBObject* temp = pbdata_;
  pbdata_ = NULL;
  return temp;
}
inline void MsgSyncRemoveData::set_allocated_pbdata(::KFMsg::PBObject* pbdata) {
  delete pbdata_;
  pbdata_ = pbdata;
  if (pbdata) {
    set_has_pbdata();
  } else {
    clear_has_pbdata();
  }
}

// -------------------------------------------------------------------

// MsgTellQueryPlayer

// required .KFMsg.PBObject player = 1;
inline bool MsgTellQueryPlayer::has_player() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTellQueryPlayer::set_has_player() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTellQueryPlayer::clear_has_player() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTellQueryPlayer::clear_player() {
  if (player_ != NULL) player_->::KFMsg::PBObject::Clear();
  clear_has_player();
}
inline const ::KFMsg::PBObject& MsgTellQueryPlayer::player() const {
  return player_ != NULL ? *player_ : *default_instance_->player_;
}
inline ::KFMsg::PBObject* MsgTellQueryPlayer::mutable_player() {
  set_has_player();
  if (player_ == NULL) player_ = new ::KFMsg::PBObject;
  return player_;
}
inline ::KFMsg::PBObject* MsgTellQueryPlayer::release_player() {
  clear_has_player();
  ::KFMsg::PBObject* temp = player_;
  player_ = NULL;
  return temp;
}
inline void MsgTellQueryPlayer::set_allocated_player(::KFMsg::PBObject* player) {
  delete player_;
  player_ = player;
  if (player) {
    set_has_player();
  } else {
    clear_has_player();
  }
}

// -------------------------------------------------------------------

// MsgTellQueryBasic

// required .KFMsg.PBObject player = 1;
inline bool MsgTellQueryBasic::has_player() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTellQueryBasic::set_has_player() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTellQueryBasic::clear_has_player() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTellQueryBasic::clear_player() {
  if (player_ != NULL) player_->::KFMsg::PBObject::Clear();
  clear_has_player();
}
inline const ::KFMsg::PBObject& MsgTellQueryBasic::player() const {
  return player_ != NULL ? *player_ : *default_instance_->player_;
}
inline ::KFMsg::PBObject* MsgTellQueryBasic::mutable_player() {
  set_has_player();
  if (player_ == NULL) player_ = new ::KFMsg::PBObject;
  return player_;
}
inline ::KFMsg::PBObject* MsgTellQueryBasic::release_player() {
  clear_has_player();
  ::KFMsg::PBObject* temp = player_;
  player_ = NULL;
  return temp;
}
inline void MsgTellQueryBasic::set_allocated_player(::KFMsg::PBObject* player) {
  delete player_;
  player_ = player;
  if (player) {
    set_has_player();
  } else {
    clear_has_player();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace KFMsg

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::KFMsg::DataProtocol>() {
  return ::KFMsg::DataProtocol_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_KFDataMessage_2eproto__INCLUDED
