#ifndef __KF_KFRAME_H__
#define __KF_KFRAME_H__

#include "KFMap.h"
#include "KFEnum.h"
#include "KFJson.h"
#include "KFField.h"
#include "KFRoute.h"
#include "KFQueue.h"
#include "KFRange.h"
#include "KFParam.h"
#include "KFVector.h"
#include "KFWeight.h"
#include "KFResult.h"
#include "KFNetData.h"
#include "KFDBValue.h"
#include "KFFunction.h"
#include "KFInstance.h"
#include "KFSingleton.h"
#include "KFProto/KFProto.h"
#include "KFUtility/KFXml.h"
#include "KFUtility/KFClock.h"
#include "KFUtility/KFDate.h"
#include "KFUtility/KFAppId.h"
#include "KFUtility/KFTimer.h"
#include "KFUtility/KFMutex.h"
#include "KFUtility/KFThread.h"
#include "KFUtility/KFCrypto.h"
#include "KFUtility/KFDecode.h"
#include "KFUtility/KFConvert.h"
#include "KFUtility/KFUtility.h"
#include "KFUtility/KFCompress.h"
#include "KFUtility/KFHash.h"
#include "KFUtility/KFStaticCondition.h"
#include "KFUtility/KFDynamicCondition.h"
#include "KFGlobal/KFGlobal.h"
#include "KFLogger/KFLogger.h"
#include "KFMemory/KFMalloc.h"
#include "KFPlugin/KFPlugin.h"
#include "KFPlugin/KFPluginManage.h"
#include "KFSetting.h"
#include "KFConfig.h"
#include "KFUtility/KFElement.h"
#include "KFExecuteData.h"


#endif