#ifndef __KF_KFRAME_H__
#define __KF_KFRAME_H__

#include "KFSystem.h"
#include "KFMacros.h"
#include "KFMap.h"
#include "KFEnum.h"
#include "KFBind.h"
#include "KFId.h"
#include "KFJson.h"
#include "KFQueue.h"
#include "KFDefine.h"
#include "KFVector.h"
#include "KFField.h"
#include "KFResult.h"
#include "KFAppID.h"
#include "KFInterfaces.h"
#include "KFSingleton.h"
#include "KFUtility/KFXml.h"
#include "KFUtility/KFClock.h"
#include "KFUtility/KFDate.h"
#include "KFUtility/KFTimer.h"
#include "KFUtility/KFCrypto.h"
#include "KFUtility/KFConvert.h"
#include "KFUtility/KFThread.h"
#include "KFUtility/KFMutex.h"
#include "KFUtility/KFUtility.h"
#include "KFUtility/KFDecode.h"
#include "KFUtility/KFCompress.h"
#include "KFGlobal/KFGlobal.h"
#include "KFPlugin/KFPlugin.h"
#include "KFConHash/KFConHash.h"
#include "KFPlugin/KFPluginManage.h"
#include "KFMemory/KFMalloc.h"


#endif